### ISSUE TITLE
코틀린 어때요

### ISSUE THREAD

**Issue by Violetdusk** [paperfrog1228/drink-of-today#1]
ㄱ??

**Comment by paperfrog1228** [comment]
아직 완성 안 했는데 잠시 퍼블릭으로 바꾼 사이 스타를 하시다니.. 철회하시고 완성하시면 다시 오십쇼
스프링 익히는 것도 지금은 벅차서 코틀린은 잠시 보류합니다ㅠㅠ

**Comment by Violetdusk** [comment]
😞
